### ISSUE TITLE
invoice not being marked paid when in https mode

### ISSUE THREAD

**Issue by kevieapps** [iammerus/paynow-whmcs#4] opened 2020-10-18 08:43 UTC
hi, i have noticed on my whmcs v7.10 but now on v8.0 when i process payment after return from paynow the invoice remains marked as not paid, but if i put my system on non https on http the invoices is successfully marked as paid. WHMCS have said its the payment module issue because seems does want to communicate which with system when the connection is https, kindly advise thanks

**Comment by mbekezm** [comment] 2020-10-18 08:47
In that case its a wise idea to keep it on https. SSL certificates are free these days.

**Comment by kevieapps** [comment] 2020-10-18 08:53
> 
> 
> In that case its a wise idea to keep it on https. SSL certificates are free these days.

yes its always on SSL/https but the payment module doesn't want to work when the system is in secure SSL mode, it seems not to communicate with whmcs that the invoice has been paid after return from payment gateway, returns no error at all, that's my dilemma

**Comment by iammerus** [comment] 2020-10-18 13:10
Hey @kevieapps. 

Can you please share the steps I can take to reproduce this on my staging environment?

**Comment by kevieapps** [comment] 2020-10-18 14:32
> 
> 
> Hey @kevieapps.
> 
> Can you please share the steps I can take to reproduce this on my staging environment?

Here is what i did, i installed the module as normal and it works well redirecting to paynow and back to whmcs after payment without any errors but the system does not mark the invoice as paid, after going around the system i noticed the setting for https or URL in  General Settings > General > WHMCS System URL > eg. https://www.example.com/members/ is that if it has **https** or the URL for secure connection the invoice will not be marked as paid even after successful return from paynow, but if the URL  is non https to eg. http://www.example.com/members/ everything will work fine and invoice will be marked as paid. So i did contact whmcs and they said the payment gateway module has to be looked at.  So it seems it doesn't want to work with a secure connection for some reason im not sure, by the way im using a subdmain e.g client.example.com not sure if that has any effect. thanks

**Comment by iammerus** [comment] 2020-10-29 18:51
@kevieapps I failed to recreate this. Perhaps we can try and schedule a session where you take me through the issue but on your environment

**Comment by kevieapps** [comment] 2020-10-29 19:16
> 
> 
> @kevieapps I failed to recreate this. Perhaps we can try and schedule a session where you take me through the issue but on your environment

Hi @iammerus that will great you can contact me via whatsapp/call +263 772 997737 to discuss further. thanks

**Comment by iammerus** [comment] 2020-11-12 14:43
@kevieapps Going to reach out directly to you and try assist. Also going to close this issue since it seems like it's isolated to your environment. Also going to delete your above comment since you posted your personal number on this public forum, to protect your privacy

**Closed as completed by iammerus** 2020-11-12 14:43 UTC
Labels: question, wontfix
